class AppStrings {
  static const _fa = {
    'login': 'ورود',
    'phone': 'شماره موبایل',
    'sendCode': 'ارسال کد',
    'verifyCode': 'تأیید کد',
    'resend': 'ارسال مجدد کد',
    'welcome': 'خوش آمدید',
    'invalidOtp': 'کد وارد شده اشتباه است',
    'Phone Number': 'شماره همراه',
    'Login/signup': 'ورود/ ایجاد حساب',
    'Email not Required': 'ایمیل (اختیاری)',
    'Sent verify code to': 'کد تایید ارسال شده به',
    'Verify code is invalid': 'کد تایید نامعتبر میباشد',
    'Verify': 'تایید',
    'Change phone ?': 'تغییر شماره ',
    'Resend verify code': 'ارسال مجدد کد',
    'Resend verify code in': 'تا ارسال مجدد کد',
    'by trading bitcoin and etc get rich': 'سرمایه گذاری در سوددهی سریع',
    'bitcoin deal': 'معاملات ارزی',
    'airplan ticket': 'بلیط هواپیما',
    'investment' : 'سرمایه گذاری',
    'dealing pay' : 'پرداخت ارزی',
    'trading' : 'ترید ارز',
    'market cap' : 'ارزش بازار فروش',
    'sherkat naft gostar' : 'شرکت گستر نفت' ,
    'medeuim risk' : 'ریسک متوسط' ,
    'sahami': 'سهامی',
    'App-menu' : 'منوی برنامه',
    'Avatar profile' : 'آواتار پروفایل',
    'Settings' : 'تنظیمات' ,
    'language' : 'زبان',
    'Dark / Light mode': 'تم تاریک / روشن',
    'Log-out' : 'خروج از حساب',
    'home' : 'خانه',
    'dollar' : 'اسکناس',
    'currency' : 'ارز و طلا' ,
    'Investment': 'سرمایه گذاری',
    'profile' : 'پروفایل' ,
    'shrkat sakhre o hamyar' : 'سرمایه صخره و دانش',
    'daramad sabet' : 'درآمد ثابت',
    'nikokari hamyar' : 'نیکوکاری همیار',
    'no risk' : 'بدون ریسک',
    'sherkat folad yekan' : 'شرکت فولاد یکان',
    'high risk' : 'ریسک بالا',
    'Dark & light mode' : 'حالت روشن و تاریک',
    'Gold' : 'قیمت لحظه ای طلا',
    'ons tala' : 'انس طلا',
    'Currency' : 'ارز و دلار'
  };

  static const _en = {
    'login': 'Login',
    'phone': 'Phone number',
    'sendCode': 'Send code',
    'verifyCode': 'Verify code',
    'resend': 'Resend code',
    'welcome': 'Welcome',
    'invalidOtp': 'Invalid code',
    'Phone Number': 'Phone Number',
    'Login/signup': 'Login/signup',
    'Email not Required':'Email not Required',
    'Sent verify code to': 'Sent verify code to',
    'Verify code is invalid': 'Verify code is invalid',
    'Verify': 'Verify',
    'Change phone ?': 'Change phone ?',
    'Resend verify code': 'Resend verify code',
    'Resend verify code in': 'Resend verify code in',
    'by trading bitcoin and etc get rich': 'by trading bitcoin and etc get rich',
    'bitcoin deal': 'bitcoin deal',
    'airplan ticket' : 'airplan ticket',
    'investment' : 'investment' ,
    'dealing pay' : 'dealing pay',
    'trading' : 'trading',
    'market cap' : 'market cap',
    'sherkat naft gostar' : 'sherkat naft gostar',
    'medeuim risk' : 'medeuim risk' ,
    'sahami' : 'sahami',
    'App-menu' : 'App-menu',
    'Avatar profile' : 'Avatar profile' ,
    'Settings' : 'Settings',
    'language' : 'language',
    'Dark / Light mode' : 'Dark / Light mode',
    'Log-out' : 'Log-out',
    'home' : 'home',
    'dollar' : 'dollar',
    'currency' : 'currency',
    'Investment' : 'Investment',
    'profile' : 'profile',
    'shrkat sakhre o hamyar' : 'shrkat sakhre o hamyar',
    'daramad sabet' : 'daramad sabet',
    'nikokari hamyar' : 'nikokari hamyar',
    'no risk' : 'no risk',
    'sherkat folad yekan' : 'sherkat folad yekan',
    'high risk' : 'high risk',
    'Dark & light mode' : 'Dark & light mode',
    'Gold' : 'Gold' ,
    'ons tala' : 'ons tala',
    'Currency' : 'Currency'

  };

  static String of(String key, bool isFa) {
    return isFa ? _fa[key]! : _en[key]!;
  }
}
